IMPORT

In [2]:
import pandas as pd
import numpy as np

QUESTION 1

In [3]:
pd.__version__

'3.0.5'

GETTING DATA

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

QUESTION 2

In [6]:
df.shape

(10000, 11)

QUESTION 3

In [7]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

QUESTION 4

In [8]:
df.isnull().any().sum()

np.int64(2)

QUESTION 5

In [9]:
df.loc[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

QUESTION 6

In [10]:
median_before = df['horsepower'].median()
median_before

np.float64(254.0)

In [11]:
horsepower_mode = df['horsepower'].mode()[0]
horsepower_mode

np.float64(252.0)

In [12]:
df['horsepower'] = df['horsepower'].fillna(horsepower_mode)

In [13]:
median_after = df['horsepower'].median()
median_after

np.float64(252.0)

QUESTION 7

In [14]:
asia_df = df.loc[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
asia_df

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [15]:
asia_df = asia_df.head(7)
asia_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [16]:
X = asia_df.to_numpy()

In [19]:
XTX = np.dot(X.T, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [22]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [32]:
XTX_inv_multiplied_XT = np.dot(XTX_inv, X.T)
XTX_inv_multiplied_XT

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [33]:
w = np.dot(XTX_inv_multiplied_XT, y)
w

array([0.13644777, 0.2327492 ])

In [34]:
w.sum()

np.float64(0.36919696904925486)